
ALTER TABLE public.trademarks
  ADD COLUMN IF NOT EXISTS description_element text,
  ADD COLUMN IF NOT EXISTS description_image text,
  ADD COLUMN IF NOT EXISTS transliteration text,
  ADD COLUMN IF NOT EXISTS translation text,
  ADD COLUMN IF NOT EXISTS note text,
  ADD COLUMN IF NOT EXISTS publication_url text,
  ADD COLUMN IF NOT EXISTS threedimensional_specification text,
  ADD COLUMN IF NOT EXISTS holographic_specification text,
  ADD COLUMN IF NOT EXISTS sound_specification text,
  ADD COLUMN IF NOT EXISTS olfactory_specification text,
  ADD COLUMN IF NOT EXISTS color_trademark_specification text,
  ADD COLUMN IF NOT EXISTS light_specification text,
  ADD COLUMN IF NOT EXISTS changing_specification text,
  ADD COLUMN IF NOT EXISTS positional_specification text,
  ADD COLUMN IF NOT EXISTS place_name_specification text,
  ADD COLUMN IF NOT EXISTS phonetics_specification text,
  ADD COLUMN IF NOT EXISTS change_right_holder_name_history text,
  ADD COLUMN IF NOT EXISTS change_right_holder_address_history text,
  ADD COLUMN IF NOT EXISTS change_correspondence_address_history text,
  ADD COLUMN IF NOT EXISTS change_legal_related_registrations_history text,
  ADD COLUMN IF NOT EXISTS change_color_specification_history text,
  ADD COLUMN IF NOT EXISTS change_disclaimer_history text,
  ADD COLUMN IF NOT EXISTS change_description_element_history text,
  ADD COLUMN IF NOT EXISTS change_description_image_history text,
  ADD COLUMN IF NOT EXISTS change_note_history text;
